### PR TITLE
Admin overhaul

### PR DESCRIPTION
**Pull request by Swamii**
- Allow `admin.register` to be called with args when used as a decorator
- Add `admin_class` as arg to `admin.register`. Makes it possible to override the `ModelAdmin` used.
- Add more admin tests.
- Make the base views (`^$`) and custom views wrapped with `AdminView.admin_view` behave the same way permission-wise.
- Test for `ModelDict.expand`
- Removed python2 stuff from compat (is that ok?)

### CODE REVIEW

**Comment by andreif** [comment]
Could you please enable Travis for your repo to see if coverage with branches works fine? Coveralls cannot do that for us unfortunately. On the other side, it's unlikely that it can drop from 100% to less than 98% 😄

**Comment by andreif** [comment]
You will need to setup Travis env vars for stasher to work, can slack you example

**Comment by Swamii** [comment]
The push build keeps failing because I keep pushing to this repo instead of my own. After the push I delete the branch here. So disregard that.

**Comment by andreif** [comment]
Hmm, I don't get why it fails.

**Comment by andreif** [comment]
Aha, you deleted the branch before travis started to test it. Okok

**Comment by andreif** [comment]
Is it included here just because it has same sha? GitHub should probably not show them here, why it does it?

**Comment by Swamii** [comment]
I have no idea. I can create a dummy commit, push to the correct origin and see if everything is green.

**Comment by andreif** [comment]
No need, the related things are green. Or maybe git amend and force push...

**Pull request merged**
