### PR TITLE
Type check project the tests are running on

### PR DESCRIPTION
**Pull request by flaeppe**
I split the content under `tests/` in 2 to only allow tests(`[mypy-tests.tests.*]`) to be excluded from type checking.

I considered type checking test cases too, but browsing quickly through the ~150 errors spewed out they're mainly hitting the `disallow_untyped_defs`-errors. So splitting it up like this felt like a reasonable compromise that'll capture meaningful  errors from type usage.

Let me know what you think.

### CODE REVIEW

**Review by antonagestam — APPROVED** [review]

**Comment by flaeppe** [comment]
> @flaeppe
> 
> > browsing quickly through the ~150 errors spewed out they're mainly hitting the `disallow_untyped_defs`-errors
> 
> We could always disable `disallow_untyped_defs` in tests? :)

Yeah, true. I did that and fixed some errors that popped up

**Comment by flaeppe** [comment]
Could perhaps be nice to move to `pytest` as that might align better mypy behaviour on native asserts:

https://github.com/5monkeys/django-bananas/blob/2295f72558e97a8c53fe06ed6861307dd9b45c84/tests/tests/drf/test_fencing.py#L186-L187

**Review by antonagestam — APPROVED** [review]

**Comment by antonagestam** [comment]
@flaeppe Yeah would be nice to introduce pytest, a little surprising though that unittest's `assertIsInstance` doesn't use `TypeGuard` in typeshed yet.

**Comment by flaeppe** [comment]
@antonagestam indeed, that's a bit surprising

**Pull request merged**
