### PR TITLE
Fix on renamed fields by ExtendedQueryset

### LINKED ISSUE #9: ExtendedQuerySet doesn't return all possible combinations when renaming reverse relation fields
This only affects the Django1.9+ version of `ExtendedQuerySet`.

Using the Parent/Child models used in the tests as an example:

```
>>> p = Parent.objects.create(name="P")
>>> c1 = Child.objects.create(parent=p, name="C1")
>>> c2 = Child.objects.create(parent=p, name="C2")

>>> Parent.objects.filter(name="P").dicts(child_name="child__name")
[{'child_name': 'C1'}, {}]

>>> # It only affects renamed fields
>>> Parent.objects.filter(name="P").dicts("child__name")
[{'child__name': 'C1'}, {'child__name': 'C2'}]
```

Attempted fix #10

### PR DESCRIPTION
**Pull request by beshrkayali**
Fixes #9

### CODE REVIEW

**Comment by andreif** [comment]
The build fails due to missing settings in Travis. Something I have not thought about...
https://travis-ci.org/beshrkayali/django-bananas/builds/221080932

**Comment by andreif** [comment]
You can create your own stasher instance via https://github.com/andreif/stasher

**Comment by andreif** [comment]
Why PR build fails is a mystery for me https://travis-ci.org/5monkeys/django-bananas/builds/221081158

**Comment by andreif** [comment]
Maybe try amend commit and force-push it to trigger a new PR build?

**Comment by beshrkayali** [comment]
Probably because `Pull requests sent from forked repositories do not have access to encrypted variables or data.` https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

**Comment by andreif** [comment]
Then we have to disable stasher for PR (`if [ "$TRAVIS_PULL_REQUEST" != "false" ];...`) or disable PR checks in Travis. Not sure why PR does not use encrypted variables from referenced repo then.

**Comment by beshrkayali** [comment]
I guess security concerns, which would make sense if the env vars are set as private (hidden from logs) on travis, otherwise if they're set as public I think PRs from forks do have access to them. Alternatively we can disable stasher for pull requests from forked repos as you suggested.

**Comment by andreif** [comment]
It's not ideal in any case https://github.com/travis-ci/travis-ci/issues/6612#issuecomment-293517304

**Comment by andreif** [comment]
Maybe I can implement JWT in Stasher and somehow ensure that only the current job may use its JWT token.

**Pull request merged**
