### PR TITLE
Add type hints

### PR DESCRIPTION
**Pull request by antonagestam**

### CODE REVIEW

**Review by hannseman — APPROVED** [review]
Superb job! 🤩

**Comment by antonagestam** [comment]
Hmm, noticed now that coverage goes down in `bananas.environment` with this patch, I'll have another look into that before merging :)

**Comment by antonagestam** [comment]
@hannseman I moved implicit dependencies to `install_requires` and removed some upper version bounds on those. Perhaps those should be extras, but that would require some inventory work and documentation, I figured it's better to just add them as requirements for now.

**Comment by hannseman** [comment]
It would be nice to be able to install this package without brining in DRF if one does not want to use the admin. 

Wouldn't a `pip install django-bananas[admin]` "just" be something like:
```
[options.extras_require]
admin =
    djangorestframework>=3.10
    drf-yasg>=1.20.0
    django-cors-headers>=3.4.0
    pytz>=2020.5
```

And then a note under https://github.com/5monkeys/django-bananas#admin about this.

**Comment by hannseman** [comment]
I wonder if we really need to include `django-cors-headers`, can't find any usage of it except for in the example project..

**Comment by antonagestam** [comment]
@hannseman That makes sense, I named the extra `drf` instead of `admin` since the fencing feature isn't admin specific but can use the same extra :)

**Review by hannseman — APPROVED** [review]
Nice!

**Pull request merged**
