### PR TITLE
Bump various dependencies

### PR DESCRIPTION
**Pull request by antonagestam**
- Drop end-of-lifed Django versions 3.0 and 3.1.
- Drop end-of-lifed Python 3.6 from test matrix.
- Bump pre-commit dependencies and set pyupgrade to --py37-plus.

### CODE REVIEW

**Comment by flaeppe** [comment]
Nice, maybe we should try out [pre-commit.ci](https://pre-commit.ci/)? Since they've deprecated their github action...

**Comment by antonagestam** [comment]
@flaeppe We could, but I'm a bit skeptical towards that, I think it's awesome to have everything running within Github Actions and I don't really understand the motivations for deprecating the action. I created a reusable workflow for running pre-commit that I [use for phantom-types](https://github.com/antonagestam/phantom-types/blob/main/.github/workflows/ci.yaml#L9-L13): https://github.com/less-action/reusables#pre-commit

Anyhow, whichever we pick I think we can do it separate from this PR :)

**Review by flaeppe — APPROVED** [review]
> @flaeppe We could, but I'm a bit skeptical towards that, I think it's awesome to have everything running within Github Actions and I don't really understand the motivations for deprecating the action. I created a reusable workflow for running pre-commit that I [use for phantom-types](https://github.com/antonagestam/phantom-types/blob/main/.github/workflows/ci.yaml#L9-L13): https://github.com/less-action/reusables#pre-commit
>
> Anyhow, whichever we pick I think we can do it separate from this PR :)

Yeah, sure. I'm merely curious really. I agree it's nicer to keep everything within GitHub actions

**Comment by flaeppe** [comment]
Btw, the PyPi release flow looks interesting there as well

**Comment by antonagestam** [comment]
> Btw, the PyPi release flow looks interesting there as well

@flaeppe Yeah it would be nice to bring something like that in here, makes it super-easy to build and publish releases, by just creating a release on Github 🙂

**Pull request merged**
